import { Article, Creator, Event, ForumComment, ForumPost, User } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Tunde Adebayo',
  username: '@tunde_creates',
  avatarUrl: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=400&q=80',
  bio: 'Visual artist and cultural documentary filmmaker based in Accra. Passionate about stories that challenge the norm.',
  interests: ['Filmmaking', 'Culture', 'Afrobeats', 'Streetwear'],
  followers: 1205,
  following: 340,
};

export const CREATORS: Creator[] = [
  {
    id: 'c1',
    name: 'Amara K.',
    role: 'Editor-in-Chief',
    avatarUrl: 'https://images.unsplash.com/photo-1531123414780-f7424ecec156?w=400&q=80',
    bio: 'Storyteller exploring the intersections of identity, culture, and modern art.',
    followers: 12400,
  },
  {
    id: 'c2',
    name: 'Chidi N.',
    role: 'Music Columnist',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    bio: 'Documenting the rise of Afrobeats, Alte, and the sounds shaping tomorrow.',
    followers: 8200,
  },
  {
    id: 'c3',
    name: 'Zainab B.',
    role: 'Style & Wellness',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
    bio: 'Advocating for slow fashion and holistic well-being for the busy millennial.',
    followers: 15300,
  },
  {
    id: 'c4',
    name: 'Kwame A.',
    role: 'Culture Correspondent',
    avatarUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400&q=80',
    bio: 'Examining cultural shifts and everyday narratives across the diaspora.',
    followers: 5900,
  }
];

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    title: 'The New Wave of African Cinema: Beyond the Trope',
    excerpt: 'How independent filmmakers are reclaiming the narrative and changing global perceptions on the big screen.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    imageUrl: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&q=80',
    category: 'Entertainment',
    readTime: '6 min read',
    date: 'Oct 24, 2023',
    authorId: 'c1',
    trending: true,
    featured: true,
  },
  {
    id: 'a2',
    title: 'Afrobeats Next Frontier: What Happens After Global Domination?',
    excerpt: 'With artists selling out arenas worldwide, what is the next evolution for the continent\'s biggest export?',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula.',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    category: 'Music',
    readTime: '4 min read',
    date: 'Oct 22, 2023',
    authorId: 'c2',
    trending: true,
  },
  {
    id: 'a3',
    title: 'Redefining Wellness: Indigenous Practices Making a Return',
    excerpt: 'From herbal remedies to mindful communal living, how ancient traditions are solving modern stress.',
    content: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-dd9fe5343722?w=800&q=80',
    category: 'Wellness',
    readTime: '5 min read',
    date: 'Oct 20, 2023',
    authorId: 'c3',
  },
  {
    id: 'a4',
    title: 'Streetwear in Lagos: The Artisans Shaping the Silhouette',
    excerpt: 'Meet the underground designers who are turning local fabrics into global hype pieces.',
    content: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    imageUrl: 'https://images.unsplash.com/photo-1509319117193-57bab727e09d?w=800&q=80',
    category: 'Fashion',
    readTime: '7 min read',
    date: 'Oct 18, 2023',
    authorId: 'c3',
    trending: true,
  },
  {
    id: 'a5',
    title: 'Finding Home: The Returnee Experience Unfiltered',
    excerpt: 'Stories of identity, struggle, and acceptance from those moving back to the continent.',
    content: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953eb1b5e4?w=800&q=80',
    category: 'Culture',
    readTime: '8 min read',
    date: 'Oct 15, 2023',
    authorId: 'c4',
    featured: true,
  },
  {
    id: 'a6',
    title: 'Tech Hubs and Creative Arts: An Unlikely Synergy',
    excerpt: 'How Nairobi\'s startup scene is quietly funding the next generation of visual artists.',
    content: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
    imageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
    category: 'News',
    readTime: '3 min read',
    date: 'Oct 12, 2023',
    authorId: 'c4',
  }
];

export const EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'The Future of Alte Sounds',
    date: 'Nov 12, 2024',
    time: '6:00 PM GMT',
    location: 'Online',
    category: 'Music',
    imageUrl: 'https://images.unsplash.com/photo-1540039155732-d67b2d56d859?w=800&q=80',
    description: 'A panel discussion with top Alte producers on global fusion.',
    isRsvpd: true,
  },
  {
    id: 'e2',
    title: 'Lagos Streetwear Expo',
    date: 'Dec 05, 2024',
    time: '12:00 PM WAT',
    location: 'Lagos, Nigeria',
    category: 'Culture',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    description: 'Showcasing the independent designers shaping the continent\'s silhouette.',
    isRsvpd: false,
  },
  {
    id: 'e3',
    title: 'Wellness & Ancestral Roots',
    date: 'Nov 20, 2024',
    time: '10:00 AM EAT',
    location: 'Nairobi, Kenya',
    category: 'Community',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    description: 'A workshop exploring how ancient practices solve modern problems.',
    isRsvpd: false,
  },
  {
    id: 'e4',
    title: 'Digital Creators Meetup',
    date: 'Jan 15, 2025',
    time: '3:00 PM GMT',
    location: 'Online',
    category: 'Online',
    imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80',
    description: 'Quarterly network event for writers, artists, and creators.',
    isRsvpd: true,
  }
];

export const FORUM_POSTS: ForumPost[] = [
  {
    id: 'p1',
    authorId: 'c1',
    content: 'Who else feels like the global definition of "African Art" is still too narrow? It always leans towards very specific traditional motifs, ignoring the incredible modern surrealism coming out of Dakar and Accra.',
    upvotes: 142,
    commentsCount: 38,
    topic: 'Culture Talk',
    timeAgo: '2 hours ago',
  },
  {
    id: 'p2',
    authorId: 'c2',
    content: 'Just listened to the new Tyla drop. Incredible production. The way Amapiano elements are subtly merged with global pop structures is a masterclass in crossover appeal.',
    upvotes: 89,
    commentsCount: 12,
    topic: 'Entertainment',
    timeAgo: '5 hours ago',
  },
  {
    id: 'p3',
    authorId: 'u1',
    content: 'Looking for advice on building a freelance portfolio as a young filmmaker. Should I focus on commercial shoots to pay the bills, or double down on passion projects like documentaries?',
    upvotes: 215,
    commentsCount: 45,
    topic: 'Creator Corner',
    timeAgo: '1 day ago',
  },
  {
    id: 'p4',
    authorId: 'c3',
    content: 'Reminder to log off: Hustle culture in our cities is reaching toxic levels. It’s okay to have a weekend where you actually just do nothing.',
    upvotes: 340,
    commentsCount: 65,
    topic: 'Wellness',
    timeAgo: '2 days ago',
  }
];

export const FORUM_COMMENTS: ForumComment[] = [
  {
    id: 'fc1',
    postId: 'p1',
    authorId: 'c4',
    content: 'Totally agree. The preoccupation with "authenticity" often results in people just wanting to see the same tropes over and over.',
    timeAgo: '1 hour ago',
    upvotes: 12,
  },
  {
    id: 'fc2',
    postId: 'p1',
    authorId: 'u1',
    content: 'I think the diaspora is actually doing a lot to change this, but the institutional gatekeepers in Europe and the US are still behind.',
    timeAgo: '45 minutes ago',
    upvotes: 8,
  },
  {
    id: 'fc3',
    postId: 'p2',
    authorId: 'c1',
    content: 'Tyla is definitely carried by that production. It\'s seamless.',
    timeAgo: '2 hours ago',
    upvotes: 5,
  }
];
